### ISSUE TITLE
for error

### ISSUE THREAD

**Issue by zm-git-dev** [sc-zhang/Text2Folder#1]
![image](https://github.com/sc-zhang/Text2Folder/assets/29561056/3bb5554d-4304-453b-90b8-810ec53ff17f)

**Comment by sc-zhang** [comment]
This is a old software which created by Visual Basic 6.0, that means there may lack Microsoft Visual Basic 6.0 Common Controls on the new windows platforms, if you want try this tool, you need find the VB6 runtime and VB6 Common Controls, and install them, then try again.
